name: palacms-testing

services:
  palacms:
    image: ${DOCKER_IMAGE}
    volumes:
      - palacms-data:/app/pb_data
    networks:
      traefik-public: null
    labels:
      - traefik.docker.network=traefik-public
      - traefik.enable=true
      - traefik.http.services.testing-palacms.loadbalancer.server.port=8080
      - traefik.http.routers.testing-palacms-http.entrypoints=http
      - traefik.http.routers.testing-palacms-http.middlewares=https-redirect
      - traefik.http.routers.testing-palacms-http.rule=Host(`testing.palacms.org`)
      - traefik.http.routers.testing-palacms-https.entrypoints=https
      - traefik.http.routers.testing-palacms-https.rule=Host(`testing.palacms.org`)
      - traefik.http.routers.testing-palacms-https.service=testing-palacms
      - traefik.http.routers.testing-palacms-https.tls=true
      - traefik.http.routers.testing-palacms-https.tls.certresolver=le

volumes:
  palacms-data:

networks:
  traefik-public:
    name: traefik-public
    external: true
